# Proste i niezawodne wdrożenie aplikacji Vite/React na GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    # Informujemy GitHub, że domyślnie ma odpalać komendy w podfolderze projektu
    defaults:
      run:
        working-directory: ./HelloKostek

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          # Wskazujemy ścieżkę do pliku lock dla poprawnego działania cache
          cache-dependency-path: "./HelloKostek/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Artefakt do wdrożenia też powstanie wewnątrz podfolderu
          path: './HelloKostek/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
